# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests - $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--configuration Debug --collect "Code coverage"'
    publishTestResults: true
    projects: 'UnitTests/UnitTests.csproj'
 
- task: BatchScript@1
  displayName: 'Publish - $(buildConfiguration)'
  inputs:
    filename: publish.bat
    
- task: GitHubRelease@0
  displayName: 'Release to GitHub'
  inputs:
    gitHubConnection: TourPlanner
    repository: Taha-cmd/superAwesomeAmazingTourPlanner
    action: edit
    target: '$(Build.SourceVersion)'
    assets: dist.zip
    tagSource: manual
    tag: '$(Build.BuildNumber)'
    

